language: haskell

sudo: false

cache:
  directories:
    - $HOME/.ghc
    - $HOME/.cabal
    - $HOME/.stack

# We test against different Stackage snapshots.
matrix:
  include:
    - env: BUILD=stack STACK_YAML=stack.yaml

    - env: BUILD=stack STACK_YAML=stack-lts-1.15.yaml

addons:
  apt:
    packages:
    - hlint
    - python
    - python-numpy

before_install:
 - export PATH=$HOME/.local/bin:$PATH
 - ./.travis-setup.sh

install:
 - stack build alex happy
 - stack --no-terminal test --only-dependencies -j 3

script:
 - stack --no-terminal test --haddock --no-haddock-deps -j 3
 - stack install

# Now for integration testing
 - data/runtests.sh # Run integration test suite.
 - data/runtests.sh --compiler=futhark-py --exclude=no_python -c # Run integration test suite with Python code generator.
 - data/runtests.sh -t --exclude=no_opencl --compiler=futhark-pyopencl # Also test OpenCL code generation

 # Let us try checking out the benchmark suite for some more tests.
 - git clone https://github.com/HIPERFIT/futhark-benchmarks.git
 - (cd futhark-benchmarks && futhark-test --travis $(find . -name '*.fut') && futhark-test --travis -t --compiler=futhark-pyopencl $(find . -name '*.fut'))

 # Check for style issues.
 - if [ "$STACK_YAML" = stack.yaml ]; then
     stack install hlint --fast && tools/style-check.sh src;
   fi

# EOF
