language: minimal
dist: trusty
git:
  submodules: false
  depth: 5
cache:
  directories:
  - "$HOME/.stack"
  - "$TRAVIS_BUILD_DIR/.stack-work"
  timeout: 1000
addons:
  apt:
    packages:
    - python
    - python-numpy
    - libgmp-dev
    - python-sphinx
    - rsync
stages:
- deps
- compiler
- tests
before_install:
- "./.travis-setup.sh"
- export PATH=$HOME/.local/bin:$PATH
jobs:
  include:
  - stage: deps
    env: BUILD=stack STACK_YAML=stack.yaml
    script: &1
    - stack build alex happy
    - stack --no-terminal test --only-dependencies -j 3
  - stage: compiler
    env: BUILD=stack STACK_YAML=stack.yaml
    script: &2
    - stack --no-terminal test -j 3
  - stage: style
    env: BUILD=stack STACK_YAML=stack.yaml
    script:
    - stack install hlint --fast
    - tools/style-check.sh src
  - stage: tests
    env: BUILD=stack STACK_YAML=stack.yaml
    script:
    - stack install
    - futhark test --no-terminal tests examples --no-tuning
    - "(cd pkgtests; ./test.sh)"
    - "(cd libtests/c; make)"
